name: Node.js CI-CD

on:
  push:
    branches: [ "master" ]
 
jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Install dependencies and build
      run: |  
        wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        sudo apt update
        sudo apt install nodejs -y
        sudo apt install npm -y
        npm run build
